export enum ActionTypes {
  BENEFITS = "BENEFITS",
  BRANCHES = "BRANCHES",
  COMPANY = "COMPANY",
  CULTURAL_FITS = "CULTURAL_FITS",
  JOB_REQUIREMENTS = "JOB_REQUIREMENTS",
  JOB_TYPE = "JOB_TYPE",
  JOB_POSITIONS = "JOB_POSITIONS",
  LANGUAGES = "LANGUAGES",
  LANGUAGE_LEVELS = "LANGUAGE_LEVELS",
  SKILLS = "SKILLS",
  SOFT_SKILLS = "SOFT_SKILLS",
}
