export enum ActionTypes {
  BENEFITS = "BENEFITS",
  BRANCHES = "BRANCHES",
  JOB_OPTIONS = "JOB_OPTIONS",
  JOB_POSITIONS = "JOB_POSITIONS",
  LANGUAGES = "LANGUAGES",
  LANGUAGE_LEVELS = "LANGUAGE_LEVELS",
  SKILLS = "SKILLS",
}
