export enum MutationTypes {
  JOB_OPTIONS_LOADING = "JOB_OPTIONS_LOADING",
  JOB_OPTIONS_LOADED = "JOB_OPTIONS_LOADED",
  BRANCHES_LOADING = "BRANCHES_LOADING",
  BRANCHES_LOADED = "BRANCHES_LOADED",
}
