export enum ActionTypes {
  ONBOARDING_STEP1 = "ONBOARDING_STEP1",
  ONBOARDING_STEP2 = "ONBOARDING_STEP2",
  ONBOARDING_STEP3 = "ONBOARDING_STEP3",
  ONBOARDING_STEP4 = "ONBOARDING_STEP4",
  ONBOARDING_STEP5 = "ONBOARDING_STEP5",
  ONBOARDING_STEP3_DATA = "ONBOARDING_STEP3_DATA",
  ONBOARDING_STEP4_DATA = "ONBOARDING_STEP4_DATA",
  CITY_BY_ZIP = "CITY_BY_ZIP",
  UPLOAD_CONFIGURATIONS = "UPLOAD_CONFIGURATIONS",
  UPLOAD_FILE = "UPLOAD_FILE",
}
