export enum MutationTypes {
  STUDENT_ONBOARDING_STEP_LOADING = "STUDENT_ONBOARDING_STEP_LOADING",
  STUDENT_ONBOARDING_STEP_LOADED = "STUDENT_ONBOARDING_STEP_LOADED",
  COMPANY_ONBOARDING_STEP_LOADING = "COMPANY_ONBOARDING_STEP_LOADING",
  COMPANY_ONBOARDING_STEP_LOADED = "COMPANY_ONBOARDING_STEP_LOADED",
  UNIVERSITY_ONBOARDING_STEP_LOADING = "UNIVERSITY_ONBOARDING_STEP_LOADING",
  UNIVERSITY_ONBOARDING_STEP_LOADED = "UNIVERSITY_ONBOARDING_STEP_LOADED",
  STUDENT_ONBOARDING_NICKNAME_SUGGESTIONS = "STUDENT_ONBOARDING_NICKNAME_SUGGESTIONS",
  ZIP_CITY_LOADING = "ZIP_CITY_LOADING",
  ZIP_CITY_LOADED = "ZIP_CITY_LOADED",
  CLEAR_ONBOARDING_STATE = "CLEAR_ONBOARDING_STATE",
}
