export enum MutationTypes {
  ONBOARDING_STEP1_LOADING = "ONBOARDING_STEP1_LOADING",
  ONBOARDING_STEP1_LOADED = "ONBOARDING_STEP1_LOADED",
  ZIP_CITY_LOADING = "ZIP_CITY_LOADING",
  ZIP_CITY_LOADED = "ZIP_CITY_LOADED",
}
