export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_TYPE = "SET_TYPE",
  REGISTRATION_CONTACT_FORM_LOADING = "REGISTRATION_CONTACT_FORM_LOADING",
  REGISTRATION_CONTACT_FORM_SENT = "REGISTRATION_CONTACT_FORM_SENT",
}
