export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_TYPE = "SET_TYPE",
  REGISTRATION_CONTACT_FORM_LOADING = "REGISTRATION_CONTACT_FORM_LOADING",
  REGISTRATION_CONTACT_FORM_SENT = "REGISTRATION_CONTACT_FORM_SENT",
  REGISTRATION_COMPANY_LOADING = "REGISTRATION_COMPANY_LOADING",
  REGISTRATION_COMPANY_LOADED = "REGISTRATION_COMPANY_LOADED",
  REGISTRATION_COMPANY_SET_CONFIRMATION = "REGISTRATION_COMPANY_SET_CONFIRMATION",
  REGISTRATION_COMPANY_SET_UID = "REGISTRATION_COMPANY_SET_UID",
  REGISTRATION_COMPANY_SET_DATA = "REGISTRATION_COMPANY_SET_DATA",
}
