export enum ActionTypes {
  SAVE_JOBPOSTING_STEP1 = "SAVE_JOBPOSTING_STEP1",
  SAVE_JOBPOSTING_STEP2 = "SAVE_JOBPOSTING_STEP2",
  SAVE_JOBPOSTING_STEP3 = "SAVE_JOBPOSTING_STEP3",
  JOBPOSTING = "JOBPOSTING",
}
