export enum MutationTypes {
  JOBPOSTING_STEP_LOADING = "JOBPOSTING_STEP_LOADING",
  JOBPOSTING_STEP_LOADED = "JOBPOSTING_STEP_LOADED",
  JOBPOSTING_LOADING = "JOBPOSTING_LOADING",
  JOBPOSTING_LOADED = "JOBPOSTING_LOADED",
}
