{{- range $variantName, $variant := .Values.deployment.variants -}}
{{- if $variant -}}
apiVersion: {{ template "deployment.apiVersion" $ }}
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "matchd-frontend.fullname" $) $variantName }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-frontend.name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-frontend.version" $ }}
    app.matchd.ch/environment: {{ template "matchd-frontend.environment" $ }}
    helm.sh/chart: {{ template "matchd-frontend.chart" $ }}
  annotations:
  {{- if $.Values.deployment.annotations }}
    {{- range $key, $value := $.Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "matchd-frontend.name" $ }}
      app.matchd.ch/environment: {{ template "matchd-frontend.environment" $ }}
  replicas: {{ $variant.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "matchd-frontend.name" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ template "matchd-frontend.version" $ }}
        app.matchd.ch/environment: {{ template "matchd-frontend.environment" $ }}
        helm.sh/chart: {{ template "matchd-frontend.chart" $ }}
      {{- if $.Values.deployment.annotations }}
      annotations:
        {{- range $key, $value := $.Values.deployment.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{ range $.Values.storages }}
        {{- if .enableBackup }}
        backup.velero.io/backup-volumes: {{ .name }}
        {{- end }}
        {{- end }}
      {{- end }}
    spec:
      imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: Always
          env:
          {{- range $key, $variable := $.Values.env -}}
            {{- $envKey := $key | upper | replace "." "_" | replace "-" "_" }}
            - name: {{ $envKey }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "matchd-frontend.fullname" $ }}
                  key: {{ $envKey }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
      affinity:
{{- if $variant.nodeAffinity }}
        nodeAffinity:
{{ toYaml $variant.nodeAffinity | indent 10 }}
{{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ template "matchd-frontend.name" $ }}
                    - key: app.matchd.ch/environment
                      operator: In
                      values:
                        - {{ template "matchd-frontend.environment" $ }}
---
{{- end }}
{{- end }}