apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "matchd-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-frontend.name" .}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-frontend.version" .}}
    app.matchd.ch/environment: {{ template "matchd-frontend.environment" .}}
    helm.sh/chart: {{ template "matchd-frontend.chart" .}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
{{- if .Values.ingress.letsencrypt }}
    cert-manager.io/acme-http01-edit-in-place: 'false'
    cert-manager.io/cluster-issuer: letsencrypt-production
{{- end }}
{{- if .Values.ingress.monitoring }}
    monitor.stakater.com/enabled: 'true'
    monitor.stakater.com/overridePath: /
{{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "matchd-frontend.fullname" $ }}
                port:
                  number: 8080
