query($slug: String) {
  company(slug: $slug) {
    id
    uid
    name
    description
    services
    street
    zip
    city
    phone
    website
    linkEducation
    linkProjects
    linkThesis
    topLevelOrganisationDescription
    topLevelOrganisationWebsite
    employees {
      id
      firstName
      lastName
      email
      role
    }
    benefits {
      id
      icon
      name
    }
    branches {
      id
      name
    }
    jobPostings {
      id
      title
      displayTitle
      jobType {
        id
        name
      }
      slug
    }
    projectPostings {
      title
      displayTitle
      slug
      topic {
        id
        name
      }
      projectType {
        id
        name
      }
    }
  }
  logo: attachments(key: COMPANY_AVATAR, slug: $slug) {
    id
    url
    mimeType
  }
  logoFallback: attachments(key: COMPANY_AVATAR_FALLBACK, slug: $slug) {
    id
    url
    mimeType
  }
  media: attachments(key: COMPANY_DOCUMENTS, slug: $slug) {
    id
    url
    mimeType
  }
}
