query($slug: String) {
  company(slug: $slug) {
    id
    uid
    name
    description
    services
    street
    zip
    city
    phone
    website
    employees {
      id
      firstName
      lastName
      email
    }
    benefits {
      id
      icon
      name
    }
    branches {
      id
      name
    }
  }
  logo: attachments(key: COMPANY_AVATAR, slug: $slug) {
    id
    url
    mimeType
  }
  media: attachments(key: COMPANY_DOCUMENTS, slug: $slug) {
    id
    url
    mimeType
  }
}
