query companyMatching {
  matches(techBoost: 3, softBoost: 3) {
    id
    name
    avatar
    type
    slug
    score
    rawScore
    title
    type
    matchStatus {
      confirmed
      initiator
    }
  }
}
