query {
  dashboard {
    projectPostings {
      id
      title
      displayTitle
      datePublished
      dateCreated
      slug
      state
      topic {
        id
        name
      }
      projectType {
        id
        name
      }
      topic {
        id
        name
      }
      company {
        name
        city
        zip
      }
      student {
        firstName
        lastName
        nickname
        zip
      }
    }
    latestJobPostings {
      id
      title
      displayTitle
      datePublished
      dateCreated
      slug
      state
      company {
        name
        city
        zip
      }
    }
    latestProjectPostings {
      id
      title
      displayTitle
      datePublished
      dateCreated
      slug
      state
      projectType {
        id
        name
      }
      topic {
        id
        name
      }
      company {
        name
        city
        zip
      }
      student {
        firstName
        lastName
        nickname
        zip
      }
    }
    jobPostings {
      id
      title
      displayTitle
      datePublished
      dateCreated
      slug
      state
      company {
        name
        city
        zip
      }
    }
    requestedMatches {
      jobPosting {
        id
        title
        displayTitle
        slug
        state
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
        firstName
        lastName
        slug
      }
    }
    unconfirmedMatches {
      jobPosting {
        id
        title
        displayTitle
        slug
        state
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
        firstName
        lastName
        slug
      }
    }
    confirmedMatches {
      jobPosting {
        id
        title
        displayTitle
        slug
        state
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
        firstName
        lastName
        slug
      }
    }
    projectMatches {
      projectPosting {
        id
        title
        displayTitle
        slug
        state
        topic {
          id
          name
        }
        projectType {
          id
          name
        }
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
        firstName
        lastName
        slug
      }
    }
  }
}
