query {
  dashboard {
    jobPostings {
      id
      title
      datePublished
      dateCreated
      slug
      company {
        name
        city
        zip
      }
    }
    requestedMatches {
      jobPosting {
        id
        title
        slug
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
      }
    }
    unconfirmedMatches {
      jobPosting {
        id
        title
        slug
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
      }
    }
    confirmedMatches {
      jobPosting {
        id
        title
        slug
        company {
          name
          city
          zip
        }
      }
      student {
        nickname
      }
    }
  }
}
