query($id: ID, $slug: String) {
  jobPosting(id: $id, slug: $slug) {
    id
    title
    description
    jobFromDate
    jobToDate
    url
    workload
    formStep
    state
    company {
      name
      street
      zip
      city
    }
    jobType {
      id
      name
    }
    branch {
      id
      name
    }
    skills {
      id
      name
    }
    jobRequirements {
      id
      name
    }
    languages {
      id
      language {
        id
        name
      }
      languageLevel {
        id
        level
        description
      }
    }
    employee {
      id
      user {
        firstName
        lastName
        email
      }
    }
  }
}
