query($id: ID, $slug: String) {
  jobPosting(id: $id, slug: $slug) {
    id
    title
    displayTitle
    description
    jobFromDate
    jobToDate
    url
    workload
    formStep
    state
    matchStatus {
      initiator
      confirmed
    }
    company {
      id
      slug
      name
      street
      zip
      city
      type
    }
    jobType {
      id
      name
    }
    branches {
      id
      name
    }
    skills {
      id
      name
    }
    jobRequirements {
      id
      name
    }
    languages {
      id
      language {
        id
        name
      }
      languageLevel {
        id
        level
        description
      }
    }
    employee {
      id
      firstName
      lastName
      email
      phone
    }
  }
}
