query (
  $studentMatchingInput: StudentMatchingInput
  $jobPostingMatchingInput: JobPostingMatchingInput
  $projectPostingMatchingInput: ProjectPostingMatchingInput
  $softBoost: Int!
  $techBoost: Int!
  $first: Int
  $skip: Int
) {
  matches(
    studentMatching: $studentMatchingInput
    jobPostingMatching: $jobPostingMatchingInput
    projectPostingMatching: $projectPostingMatchingInput
    first: $first
    skip: $skip
    softBoost: $softBoost
    techBoost: $techBoost
  ) {
    name
    title
    description
    keywords {
      id
      name
    }
    avatar
    type
    slug
    score
    rawScore
    matchStatus {
      confirmed
      initiator
    }
  }
}
