query {
  me {
    id
    firstName
    lastName
    username
    email
    type
    student {
      id
      city
      zip
      street
      email
      mobile
      dateOfBirth
      jobFromDate
      jobToDate
      distinction
      fieldOfStudy
      graduation
      profileStep
      nickname
      state
      branch {
        id
        name
      }
      culturalFits {
        id
      }
      languages {
        language {
          id
          name
        }
        languageLevel {
          id
          level
        }
      }
      onlineProjects {
        id
        url
      }
      hobbies {
        id
        name
      }
      jobType {
        id
        name
      }
      skills {
        id
      }
      softSkills {
        id
      }
    }
    employee {
      id
      role
    }
    company {
      id
      name
      city
      zip
      street
      profileStep
      state
      jobPostings {
        id
        slug
        title
        state
      }
    }
  }
}
