query {
  me {
    id
    firstName
    lastName
    username
    email
    type
    student {
      id
      city
      zip
      street
      email
      mobile
      dateOfBirth
      jobFromDate
      jobToDate
      distinction
      fieldOfStudy
      graduation
      profileStep
      nickname
      state
      branch {
        id
        name
      }
      culturalFits(first: 200) {
        edges {
          node {
            id
          }
        }
      }
      languages(first: 200) {
        edges {
          node {
            language {
              id
              name
            }
            languageLevel {
              id
              level
            }
          }
        }
      }
      onlineProjects {
        id
        url
      }
      hobbies {
        id
        name
      }
      jobType {
        id
        name
        mode
      }
      skills(first: 200) {
        edges {
          node {
            id
            name
          }
        }
      }
      softSkills(first: 200) {
        edges {
          node {
            id
          }
        }
      }
    }
    employee {
      id
      role
      firstName
      lastName
      phone
      email
    }
    company {
      id
      name
      displayName
      city
      zip
      street
      profileStep
      state
      description
      website
      memberItStGallen
      topLevelOrganisationWebsite
      topLevelOrganisationDescription
      services
      phone
      employees {
        firstName
        lastName
        email
        role
      }
      jobPostings {
        id
        slug
        title
        state
        jobType {
          id
          name
        }
      }
      projectPostings {
        id
        title
        state
        projectType {
          id
          name
        }
        topic {
          id
          name
        }
      }
      branches(first: 200) {
        edges {
          node {
            id
            name
          }
        }
      }
      benefits(first: 200) {
        edges {
          node {
            id
            icon
            name
          }
        }
      }
      culturalFits {
        id
      }
      softSkills {
        id
      }
      linkEducation
      linkProjects
      linkThesis
    }
  }
}
