fragment projectPostingProjectPosting on ProjectPosting {
  id
  slug
  title
  displayTitle
  description
  teamSize
  compensation
  formStep
  state
  projectFromDate
  datePublished
  website
  matchStatus {
    initiator
    confirmed
  }
  keywords {
    id
    name
  }
  projectType {
    id
    name
  }
  keywords {
    id
    name
  }
  company {
    id
    slug
    name
    street
    zip
    city
  }
  student {
    id
    slug
    firstName
    lastName
    nickname
    city
  }
  employee {
    id
    firstName
    lastName
    email
    phone
    role
  }
}

fragment projectPostingImage on Attachment {
  id
  fileName
  url
  mimeType
}

fragment projectPostingImageFallback on Attachment {
  id
  fileName
  url
  mimeType
}

fragment projectPostingDocument on Attachment {
  id
  fileName
  url
  mimeType
}
