#import "./projectPostingFragment.gql"

query projectPosting ($id: String, $slug: String) {
  projectPosting(id: $id, slug: $slug) {
    ...projectPosting
  }
  images: attachments(key: PROJECT_POSTING_IMAGES, slug: $slug, first: 100) {
    edges {
      node {
        ...projectPostingImage
      }
    }
  }
  imageFallback: attachments(key: PROJECT_POSTING_FALLBACK, slug: $slug, first: 100) {
    edges {
      node {
        ...projectPostingImageFallback
      }
    }
  }
  documents: attachments(key: PROJECT_POSTING_DOCUMENTS, slug: $slug, first: 100) {
    edges {
      node {
        ...projectPostingDocument
      }
    }
  }
}
