fragment studentStudent on Student {
  id
  email
  mobile
  slug
  state
  firstName
  lastName
  street
  zip
  city
  dateOfBirth
  nickname
  schoolName
  fieldOfStudy
  graduation
  distinction
  profileStep
  jobFromDate
  jobToDate
  isMatchable
  matchStatus {
    initiator
    confirmed
  }
  branch {
    name
    id
  }
  jobType {
    name
    id
    mode
  }
  skills(first: 100) {
    edges {
      node {
        id
        name
      }
    }
  }
  softSkills(first: 100) {
    edges {
      node {
        id
        student
        company
      }
    }
  }
  culturalFits(first: 100) {
    edges {
      node {
        id
        company
        student
      }
    }
  }
  hobbies {
    id
    name
  }
  onlineChallenges {
    id
    url
  }
  languages(first: 100) {
    edges {
      node {
        id
        language {
          name
          id
        }
        languageLevel {
          level
          id
        }
      }
    }
  }
  challenges {
    id
    title
    displayTitle
    slug
    keywords {
      id
      name
    }
    challengeType {
      id
      name
    }
  }
}

fragment studentAvatar on Attachment {
  id
  url
  mimeType
}

fragment studentAvatarFallback on Attachment {
  id
  url
  mimeType
}

fragment studentCertificates on Attachment {
  id
  url
  mimeType
  fileName
}
