# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
version:
name:
fullname:
environment:
releaseLabel:
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
deployment:
  annotations: {}
  variants:
    stable:
      replicaCount: 0
      autoscaling:
        enabled: false
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: DoesNotExist
    regular:
      replicaCount: 1
      autoscaling:
        enabled: true
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: Exists
            weight: 100
ingress:
  # domain: my.host.com
  letsencrypt: false
  monitoring: false
  tlsSecretName: chart-example-tls
env: {}
