export enum MutationTypes {
  CONFIGURATIONS_LOADING = "CONFIGURATIONS_LOADING",
  CONFIGURATIONS_LOADED = "CONFIGURATIONS_LOADED",
  ADD_FILE_TO_QUEUE = "ADD_FILE_TO_QUEUE",
  UPLOAD_FILE_START = "UPLOAD_FILE_START",
  UPLOAD_FILE_COMPLETE = "UPLOAD_FILE_COMPLETE",
  UPLOADED_FILES_LOADING = "UPLOADED_FILES_LOADING",
  UPLOADED_FILES_LOADED = "UPLOADED_FILES_LOADED",
  DELETE_FILE_LOADING = "DELETE_FILE_LOADING",
  DELETE_FILE_LOADED = "DELETE_FILE_LOADED",
}
