export enum MutationTypes {
  LOGIN_LOADING = "LOGIN_LOADING",
  LOGIN_LOADED = "LOGIN_LOADED",
  REFRESH_LOGIN_LOADING = "REFRESH_LOGIN_LOADING",
  REFRESH_LOGIN_LOADED = "REFRESH_LOGIN_LOADED",
  ME_LOADING = "ME_LOADING",
  ME_LOADED = "ME_LOADED",
}
