on:
  push:
    branches:
      - "main"

name: "Main Branch"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml

  deploy:
    name: "Deploy"

    needs: ["build"]

    uses: ./.github/workflows/part_deploy.yml
    with:
      namespace: matchd-frontend-development
      release: matchd-frontend
      environment: development
      letsencryptEnabled: true
      domain: development.matchd.ch
      apiUrl: "https://api.development.matchd.ch"
      gtmContainerId: "${{ vars.GTM_CONTAINER_ID }}"
      sentryDsn: "${{ vars.SENTRY_DSN }}"
    secrets:
      DOCKER_PULL_USERNAME: "${{ secrets.DOCKER_PULL_USERNAME }}"
      DOCKER_PULL_SECRET: "${{ secrets.DOCKER_PULL_SECRET }}"
