on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEFAULT_NODEJS_VERSION: 16.13.1

jobs:
  test:
    name: "Tests"

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.DEFAULT_NODEJS_VERSION }}"

      - id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run test suite
        run: npm run test:unit
  
  lint:
    name: "Lint"

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.DEFAULT_NODEJS_VERSION }}"

      - id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run test suite
        run: npm run lint

  automerge_dependabot:
    name: "Automerge Dependabot PRs"

    runs-on: ubuntu-latest

    needs: ['test', 'lint']

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Major Updates need to be merged manually
          target: minor
