on:
  workflow_call: {}

name: "Test"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

env:
  DEFAULT_NODEJS_VERSION: 16.13.1

jobs:
  test:
    name: "Unit Tests"

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "${{ env.DEFAULT_NODEJS_VERSION }}"

      - id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run test suite
        run: npm run test:unit

  lint:
    name: "Lint"

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        id: setup-node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "${{ env.DEFAULT_NODEJS_VERSION }}"

      - id: cache-npm
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ secrets.CACHE_VERSION }}-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Run Linter
        run: npm run lint -- --no-fix
