on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      release:
        required: true
        type: string
      environment:
        required: true
        type: string
      regularReplicaCount:
        default: 1
        type: number
      stableReplicaCount:
        default: 0
        type: number
      version:
        default: "${{ github.sha }}"
        type: string
      domain:
        required: true
        type: string
      letsencryptEnabled:
        type: boolean
        default: false
      monitoringEnabled:
        type: boolean
        default: false
      autoscalingEnabled:
        type: boolean
        default: false
      gtmEnabled:
        type: boolean
        default: false
      gtmDebug:
        type: boolean
        default: false
      task:
        type: string
        default: apply
      apiUrl:
        type: string
        required: true
      gtmContainerId:
        type: string
        required: true
      sentryDsn:
        type: string
        required: true
      commentDeployment:
        type: boolean
        default: false
    secrets:
      DOCKER_PULL_USERNAME:
        required: true
      DOCKER_PULL_SECRET:
        required: true

jobs:
  deploy_review:
    name: "Helm"

    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          HELMFILE_VERSION="$(cat .tool-versions | grep "helmfile " | cut -d' ' -f2-)"
          echo "HELMFILE_VERSION=${HELMFILE_VERSION}" >> $GITHUB_ENV

          HELM_VERSION="$(cat .tool-versions | grep "helm " | cut -d' ' -f2-)"
          echo "HELM_VERSION=${HELM_VERSION}" >> $GITHUB_ENV

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.3.0
        with:
          helmfile-version: "v${{ env.HELMFILE_VERSION }}"
          helm-version: "v${{ env.HELM_VERSION }}"
          install-kubectl: "no"

      - uses: google-github-actions/setup-gcloud@v0.6.2
        with:
          project_id: "joshmartin-cluster"

      - name: "Prepare Helm Chart"
        run: "helm dependency update .helm/chart/"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2.1.4"
        with:
          workload_identity_provider: "projects/182803428686/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "matchd-deployer@joshmartin-cluster.iam.gserviceaccount.com"

      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v0.8.2"
        with:
          cluster_name: "joshmartin-cluster-next"
          location: "europe-west6-a"

      - name: "Create Pull Secret"
        if: ${{ inputs.task != 'remove' }}
        run: |
          kubectl create secret --namespace="${{ inputs.namespace }}" \
            docker-registry \
            "${{ inputs.release }}-pull" \
            --docker-server="ghcr.io" \
            --docker-username="${{ secrets.DOCKER_PULL_USERNAME }}" \
            --docker-password="${{ secrets.DOCKER_PULL_SECRET }}" \
            --output=yaml \
            --dry-run=client \
            | kubectl \
              replace \
              --namespace="${{ inputs.namespace }}" \
              --force \
              --filename=-

      - name: "Deploy"
        run: helmfile --file .helm/helmfile.yaml ${{ inputs.task }}
        env:
          VALUE_SENTRY_DSN: "${{ inputs.sentryDsn }}"
          VALUE_GTM_CONTAINER_ID: "${{ inputs.gtmContainerId }}"
          VALUE_GTM_DEBUG: "${{ inputs.gtmDebug }}"
          VALUE_GTM_ENABLED: "${{ inputs.gtmEnabled }}"
          VALUE_API_URL: "${{ inputs.apiUrl }}"
          VALUE_MONITORING_ENABLED: "${{ inputs.monitoringEnabled }}"
          VALUE_LETS_ENCRYPT_ENABLED: "${{ inputs.letsencryptEnabled }}"
          VALUE_DOMAIN: "${{ inputs.domain }}"
          VALUE_IMAGE_REPOSITORY: "ghcr.io/${{ github.repository }}"
          HELM_RELEASE_NAME: "${{ inputs.release }}"
          VALUE_ENVIRONMENT: "${{ inputs.environment }}"
          VALUE_STABLE_AUTOSCALING_ENABLED: "${{ inputs.autoscalingEnabled }}"
          VALUE_STABLE_REPLICA_COUNT: "${{ inputs.stableReplicaCount }}"
          VALUE_REGULAR_AUTOSCALING_ENABLED: "${{ inputs.autoscalingEnabled }}"
          VALUE_REGULAR_REPLICA_COUNT: "${{ inputs.regularReplicaCount }}"
          HELM_RELEASE_VERSION: "${{ inputs.version }}"
          KUBE_NAMESPACE: "${{ inputs.namespace }}"
          KUBE_CONTEXT: "gke_joshmartin-cluster_europe-west6-a_joshmartin-cluster-next"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: "${{ inputs.commentDeployment }}"
        with:
          message: "Deployed to https://${{ inputs.domain }}"
          comment_tag: "deployment"
