on:
  pull_request:
    branches:
      - "*"

name: "Pull Request"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml

  dependabot:
    name: "Dependabot"

    if: ${{ github.actor == 'dependabot[bot]'}}

    uses: ./.github/workflows/part_dependabot.yml

  deploy:
    name: "Deploy"

    if: ${{ github.actor != 'dependabot[bot]'}}

    needs: ["build"]

    uses: ./.github/workflows/part_deploy.yml
    with:
      namespace: matchd-frontend-review
      release: review-matchd-frontend-${{ github.event.pull_request.number }}
      environment: review-${{ github.event.pull_request.number }}
      domain: review-matchd-frontend-${{ github.event.pull_request.number }}.joshmartin.ch
      apiUrl: "https://api.development.matchd.ch"
      gtmContainerId: "${{ vars.GTM_CONTAINER_ID }}"
      sentryDsn: "${{ vars.SENTRY_DSN }}"
      commentDeployment: true
    secrets:
      DOCKER_PULL_USERNAME: "${{ secrets.DOCKER_PULL_USERNAME }}"
      DOCKER_PULL_SECRET: "${{ secrets.DOCKER_PULL_SECRET }}"
