on:
  pull_request:
    branches:
      - "*"

name: "Pull Request"

jobs:
  # test:
  #   name: "Test"

  #   # TODO: Change to main
  #   uses: matchd-ch/matchd-frontend/.github/workflows/part_test.yml@deploy
  
  build:
    name: "Build"

    # TODO: Change to main
    uses: matchd-ch/matchd-frontend/.github/workflows/part_build.yml@deploy
  
  # dependabot:
  #   name: "Dependabot"

  #   needs: ['test', 'build']

  #   # TODO: Change to main
  #   uses: matchd-ch/matchd-frontend/.github/workflows/part_dependabot.yml@deploy

  deploy:
    name: "Deploy"

    needs: ['build']

    # TODO: Change to main
    uses: matchd-ch/matchd-frontend/.github/workflows/part_deploy.yml@deploy
    with:
      namespace: matchd-frontend-review
      release: review-matchd-frontend-${{ github.event.pull_request.number }}
      environment: review-${{ github.event.pull_request.number }}
      domain: eview-matchd-frontend-${{ github.event.pull_request.number }}.joshmartin.ch
      apiUrl: "https://development-matchd-backend.joshmartin.ch/"
    secrets:
      DOCKER_PULL_USERNAME: ${{ secrets.DOCKER_PULL_USERNAME }}
      DOCKER_PULL_SECRET: ${{ secrets.DOCKER_PULL_SECRET }}