on:
  pull_request:
    types: [closed]

name: "Pull Request Cleanup"

jobs:
  undeploy:
    name: "Undeploy"

    concurrency: review-${{ github.event.pull_request.number }}

    uses: ./.github/workflows/part_deploy.yml
    with:
      namespace: matchd-frontend-review
      release: review-matchd-frontend-${{ github.event.pull_request.number }}
      environment: review-${{ github.event.pull_request.number }}
      domain: review-matchd-frontend-${{ github.event.pull_request.number }}.joshmartin.ch
      apiUrl: "https://development.matchd.ch"
      task: destroy
      gtmContainerId: "${{ vars.GTM_CONTAINER_ID }}"
      sentryDsn: "${{ vars.SENTRY_DSN }}"
    secrets:
      DOCKER_PULL_USERNAME: "${{ secrets.DOCKER_PULL_USERNAME }}"
      DOCKER_PULL_SECRET: "${{ secrets.DOCKER_PULL_SECRET }}"
