on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+-beta.[0-9]+"

name: "Beta Tag"

jobs:
  build:
    name: Build

    uses: ./.github/workflows/part_build.yml

  deploy:
    name: "Deploy"

    needs: ["build"]

    uses: ./.github/workflows/part_deploy.yml
    with:
      namespace: matchd-frontend-staging
      release: matchd-frontend
      environment: staging
      letsencryptEnabled: true
      domain: staging.matchd.ch
      version: "${{ needs.build.outputs.tag }}"
      apiUrl: "https://api.staging.matchd.ch"
      gtmContainerId: "${{ vars.GTM_CONTAINER_ID }}"
      sentryDsn: "${{ vars.SENTRY_DSN }}"
    secrets:
      DOCKER_PULL_USERNAME: "${{ secrets.DOCKER_PULL_USERNAME }}"
      DOCKER_PULL_SECRET: "${{ secrets.DOCKER_PULL_SECRET }}"
