on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+-beta.[0-9]+"

name: "Beta Tag"

jobs:
  build:
    name: Build

    uses: matchd-ch/matchd-frontend/.github/workflows/part_build.yml@main

  deploy:
    name: "Deploy"

    needs: ['build']

    environment:
      name: staging
      url: https://staging-matchd-frontend.joshmartin.ch

    concurrency: staging

    uses: matchd-ch/matchd-frontend/.github/workflows/part_deploy.yml@main
    with:
      namespace: matchd-frontend-staging
      release: matchd-frontend
      environment: staging
      domain: staging-matchd-frontend.joshmartin.ch
      version: "${{ needs.build.outputs.tag }}"
      apiUrl: "https://staging-matchd-backend.joshmartin.ch/"
    secrets:
      DOCKER_PULL_USERNAME: ${{ secrets.DOCKER_PULL_USERNAME }}
      DOCKER_PULL_SECRET: ${{ secrets.DOCKER_PULL_SECRET }}