on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml

  deploy:
    name: "Deploy"

    needs: ["build"]

    uses: ./.github/workflows/part_deploy.yml
    with:
      namespace: matchd-frontend-production
      release: matchd-frontend
      environment: production
      domain: get.matchd.ch
      regularReplicaCount: 2
      letsencryptEnabled: true
      monitoringEnabled: true
      autoscalingEnabled: true
      version: "${{ needs.build.outputs.tag }}"
      apiUrl: "https://api.matchd.ch"
      gtmEnabled: true
      gtmContainerId: "${{ vars.GTM_CONTAINER_ID }}"
      sentryDsn: "${{ vars.SENTRY_DSN }}"
    secrets:
      DOCKER_PULL_USERNAME: "${{ secrets.DOCKER_PULL_USERNAME }}"
      DOCKER_PULL_SECRET: "${{ secrets.DOCKER_PULL_SECRET }}"
