on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  build:
    name: "Build"

    uses: matchd-ch/matchd-frontend/.github/workflows/part_build.yml@main

  deploy:
    name: "Deploy"

    needs: ['build']

    uses: matchd-ch/matchd-frontend/.github/workflows/part_deploy.yml@main
    with:
      namespace: matchd-frontend-production
      release: matchd-frontend
      environment: production
      domain: matchd.ch
      regularReplicaCount: 2
      letsencryptEnabled: true
      monitoringEnabled: true
      autoscalingEnabled: true
      version: "${{ needs.build.outputs.tag }}"
      apiUrl: "https://api.matchd.ch"
    secrets:
      DOCKER_PULL_USERNAME: ${{ secrets.DOCKER_PULL_USERNAME }}
      DOCKER_PULL_SECRET: ${{ secrets.DOCKER_PULL_SECRET }}
